name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name tarekacr001

      - name: Build Docker Image
        run: |
          docker build \
            -t tarekacr001.azurecr.io/demo:${{ github.sha }} \
            -t tarekacr001.azurecr.io/demo:latest \
            ./app

      - name: Push Latest
        run: |
          docker push tarekacr001.azurecr.io/demo:latest

      - name: Push Version
        run: |
          docker push tarekacr001.azurecr.io/demo:${{ github.sha }}

      - name: Show Repositories
        run: |
          az acr repository list \
            --name tarekacr001 \
            --output table
